version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: anton
    main: .
    binary: anton
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: binary
    format: binary
    name_template: "anton-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
